'use client';
import React from 'react';
import { BadgeCheck,BookOpen,ChevronRight,GraduationCap,KeyRound,LogOut,Mail,MapPin,Phone,Save,ShieldCheck,Trash2,Users } from 'lucide-react';
import { useRouter } from 'next/navigation';
import { Card,PageHeader } from '@/components/ui';
import { useTelegram } from '@/components/providers/TelegramProvider';
import { AccountPreferences } from '@/lib/types';
export default function ProfilePage(){const router=useRouter();const{user,stats,updateUser,logout}=useTelegram();const[editing,setEditing]=React.useState(false);const[form,setForm]=React.useState({fullName:user?.full_name||'',schoolName:user?.school_name||'',region:user?.region||'',district:user?.district||'',subject:user?.subject||''});const[prefs,setPrefs]=React.useState<AccountPreferences>(user?.preferences||{language:'uz',theme:'system',notifications:true,default_max_score:20});const[status,setStatus]=React.useState('');const[link,setLink]=React.useState<'phone'|'email'|null>(null);const[value,setValue]=React.useState('');const[token,setToken]=React.useState('');const[sent,setSent]=React.useState(false);const[loginName,setLoginName]=React.useState(user?.username||'');const[loginPassword,setLoginPassword]=React.useState('');if(!user)return null;
 const saveProfile=async()=>{const r=await fetch('/api/profile',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const d=await r.json();if(r.ok){updateUser(d.user);setEditing(false);setStatus('Profil saqlandi')}else setStatus(d.error)};
 const savePrefs=async()=>{const r=await fetch('/api/account',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(prefs)});const d=await r.json();if(r.ok){updateUser(d.user);setStatus('Sozlamalar saqlandi')}else setStatus(d.error)};
 const saveLogin=async()=>{const r=await fetch('/api/auth/password',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:loginName.trim().toLowerCase(),password:loginPassword})});const d=await r.json();if(r.ok){updateUser(d.user);setLoginPassword('');setStatus('Username va parol saqlandi')}else setStatus(d.error)};
 const send=async()=>{const r=await fetch('/api/auth/otp/send',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({channel:link,value,purpose:'link'})});const d=await r.json();if(r.ok)setSent(true);else setStatus(d.error)};const verify=async()=>{const r=await fetch('/api/auth/otp/verify',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({channel:link,value,token,purpose:'link'})});const d=await r.json();if(r.ok){updateUser(d.user);setLink(null);setStatus('Login usuli ulandi')}else setStatus(d.error)};
 const remove=async()=>{const confirmation=prompt("Bu amal qaytarilmaydi. Davom etish uchun AKKAUNTNI O'CHIRISH deb yozing:");if(!confirmation)return;const r=await fetch('/api/account',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({confirmation})});const d=await r.json();if(!r.ok){alert(d.error||'Akkaunt o‘chirilmadi');return}router.push('/auth/recover')};
 const input='mt-1.5 min-h-11 w-full rounded-[10px] border bg-transparent px-3 text-sm outline-none';return <div className="animate-page-in mx-auto max-w-3xl space-y-6"><PageHeader title="Profil va sozlamalar" description="Akkauntingiz, login usullari va ilova sozlamalari."/>{status&&<div role="status" className="rounded-[10px] border bg-[var(--surface)] p-3 text-sm">{status}</div>}
  <Card className="p-5 sm:p-6"><div className="flex items-center gap-4"><div className="app-muted flex h-14 w-14 items-center justify-center rounded-full text-lg font-semibold">{user.full_name.split(' ').map(x=>x[0]).slice(0,2).join('')}</div><div className="min-w-0 flex-1"><h2 className="truncate text-lg font-semibold">{user.full_name}</h2><p className="mt-1 text-sm text-muted">{user.school_name||'Maktab kiritilmagan'} · {user.subject||'Fan tanlanmagan'}</p></div><button onClick={()=>setEditing(!editing)} className="min-h-10 rounded-[9px] border px-3 text-xs font-medium">{editing?'Bekor qilish':'Tahrirlash'}</button></div>{editing&&<div className="mt-6 grid gap-4 sm:grid-cols-2"><Field label="Ism va familiya"><input className={input} value={form.fullName} onChange={e=>setForm({...form,fullName:e.target.value})}/></Field><Field label="Maktab"><input className={input} value={form.schoolName} onChange={e=>setForm({...form,schoolName:e.target.value})}/></Field><Field label="Viloyat"><input className={input} value={form.region} onChange={e=>setForm({...form,region:e.target.value})}/></Field><Field label="Tuman / shahar"><input className={input} value={form.district} onChange={e=>setForm({...form,district:e.target.value})}/></Field><Field label="Asosiy fan"><input className={input} value={form.subject} onChange={e=>setForm({...form,subject:e.target.value})}/></Field><button onClick={saveProfile} className="mt-auto flex min-h-11 items-center justify-center gap-2 rounded-[10px] bg-primary text-sm font-medium text-white"><Save className="h-4 w-4"/>Saqlash</button></div>}</Card>
  <Section title="Akkaunt"><Card className="divide-y"><AccountRow icon={<BadgeCheck/>} label="Telegram" value={user.telegram_id?'Ulangan':'Ulanmagan'} verified={!!user.telegram_id}/><AccountRow icon={<Phone/>} label="Telefon" value={user.phone||'Ulanmagan'} verified={!!user.phone} action={()=>setLink('phone')}/><AccountRow icon={<Mail/>} label="Email" value={user.email||'Ulanmagan'} verified={!!user.email} action={()=>setLink('email')}/></Card></Section>
  <Section title="Username va parol"><Card className="p-5"><div className="flex items-start gap-3"><KeyRound className="mt-1 h-5 w-5 text-primary"/><div><p className="text-sm font-medium">{user.username?'Login ma\u2019lumotlarini yangilash':'Brauzerdan kirishni yoqish'}</p><p className="mt-1 text-xs leading-5 text-muted">Username va yangi parol kiriting. Parol kamida 8 ta belgi bo‘lsin.</p></div></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><Field label="Username"><input className={input} value={loginName} onChange={e=>setLoginName(e.target.value.replace(/[^a-zA-Z0-9_]/g,'').toLowerCase())} placeholder="aziza_ustoz"/></Field><Field label="Yangi parol"><input type="password" className={input} value={loginPassword} onChange={e=>setLoginPassword(e.target.value)} placeholder="Kamida 8 ta belgi"/></Field></div><button onClick={saveLogin} disabled={loginName.length<3||loginPassword.length<8} className="mt-4 min-h-11 rounded-[10px] bg-primary px-4 text-sm font-medium text-white disabled:opacity-40">Username va parolni saqlash</button></Card></Section>
  {link&&<Card className="p-5"><h3 className="text-sm font-semibold">{link==='phone'?'Telefon ulash':'Email ulash'}</h3><input className={input} value={value} onChange={e=>setValue(e.target.value)} placeholder={link==='phone'?'+998 90 123 45 67':'siz@email.uz'}/>{sent&&<input className={`${input} text-center tracking-[.4em]`} value={token} onChange={e=>setToken(e.target.value.replace(/\D/g,'').slice(0,6))} placeholder="000000"/>}<div className="mt-3 flex gap-2"><button onClick={()=>setLink(null)} className="min-h-11 rounded-[10px] border px-4 text-sm">Bekor qilish</button><button onClick={sent?verify:send} className="min-h-11 flex-1 rounded-[10px] bg-primary text-sm text-white">{sent?'Tasdiqlash':'Kod yuborish'}</button></div></Card>}
  <Section title="Ma’lumotlar"><div className="grid grid-cols-3 overflow-hidden rounded-[14px] border bg-[var(--border)] gap-px"><Stat icon={<GraduationCap/>} label="Sinflar" value={stats.classCount}/><Stat icon={<Users/>} label="O‘quvchilar" value={stats.studentCount}/><Stat icon={<BookOpen/>} label="Tekshiruvlar" value={stats.totalChecked}/></div></Section>
  <Section title="Tarif"><Card className="flex items-center gap-4 p-5"><span className="app-muted flex h-11 w-11 items-center justify-center rounded-[10px] text-primary"><ShieldCheck className="h-5 w-5"/></span><div className="flex-1"><p className="text-sm font-semibold">FREE</p><p className="mt-1 text-xs text-muted">{stats.totalChecked} / 50 oylik tekshiruv</p></div><button className="min-h-10 rounded-[9px] border px-3 text-xs font-medium">Tarifni boshqarish</button></Card></Section>
  <Section title="Sozlamalar"><Card className="space-y-4 p-5"><div className="grid gap-4 sm:grid-cols-2"><Field label="Til"><select className={input} value={prefs.language} onChange={e=>setPrefs({...prefs,language:e.target.value as any})}><option value="uz">O‘zbekcha</option><option value="ru">Русский</option></select></Field><Field label="Mavzu"><select className={input} value={prefs.theme} onChange={e=>setPrefs({...prefs,theme:e.target.value as any})}><option value="system">Tizim bo‘yicha</option><option value="light">Yorug‘</option><option value="dark">Qorong‘i</option></select></Field><Field label="Standart maksimal ball"><input type="number" min="1" max="100" className={input} value={prefs.default_max_score} onChange={e=>setPrefs({...prefs,default_max_score:Number(e.target.value)})}/></Field><label className="flex min-h-11 items-center justify-between rounded-[10px] border px-3 text-sm">Bildirishnomalar<input type="checkbox" checked={prefs.notifications} onChange={e=>setPrefs({...prefs,notifications:e.target.checked})} className="h-4 w-4"/></label></div><button onClick={savePrefs} className="min-h-11 rounded-[10px] bg-primary px-4 text-sm font-medium text-white">Sozlamalarni saqlash</button></Card></Section>
  <Section title="Akkaunt boshqaruvi"><Card className="divide-y"><button onClick={async()=>{await logout();router.push('/auth/recover')}} className="flex min-h-14 w-full items-center gap-3 px-4 text-left text-sm"><LogOut className="h-4 w-4"/>Akkauntdan chiqish<ChevronRight className="ml-auto h-4 w-4 text-muted"/></button><div className="p-4"><p className="text-sm font-medium text-red-600">Xavfli hudud</p><p className="mt-1 text-xs leading-5 text-muted">O‘chirish so‘rovidan keyin akkaunt 14 kun davomida tiklanishi mumkin.</p><button onClick={remove} className="mt-3 flex min-h-10 items-center gap-2 rounded-[9px] border border-red-200 px-3 text-xs font-medium text-red-600"><Trash2 className="h-4 w-4"/>Akkauntni o‘chirish</button></div></Card></Section>
 </div>}
function Section({title,children}:{title:string;children:React.ReactNode}){return <section><h2 className="mb-3 text-sm font-semibold">{title}</h2>{children}</section>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="text-xs font-medium">{label}{children}</label>}
function AccountRow({icon,label,value,verified,action}:{icon:React.ReactNode;label:string;value:string;verified:boolean;action?:()=>void}){return <div className="flex min-h-16 items-center gap-3 px-4"><span className="[&>svg]:h-4 [&>svg]:w-4 text-muted">{icon}</span><div className="flex-1"><p className="text-sm font-medium">{label}</p><p className="mt-0.5 text-xs text-muted">{value}</p></div>{verified?<span className="flex items-center gap-1 text-xs text-emerald-600"><BadgeCheck className="h-4 w-4"/>Tasdiqlangan</span>:<button onClick={action} className="min-h-9 rounded-[8px] border px-3 text-xs">Ulash</button>}</div>}
function Stat({icon,label,value}:{icon:React.ReactNode;label:string;value:number}){return <div className="app-surface p-4 text-center"><span className="mx-auto block w-fit [&>svg]:h-4 [&>svg]:w-4 text-muted">{icon}</span><p className="mt-2 text-xl font-semibold">{value}</p><p className="mt-1 text-[11px] text-muted">{label}</p></div>}
