'use client';
import React, { Suspense } from 'react';
import Link from 'next/link';
import { useSearchParams } from 'next/navigation';
import { ArrowRight, BookOpen, Plus, Search, Users } from 'lucide-react';
import { ClassItem } from '@/lib/types';
import { CreateClassModal } from '@/components/classes/CreateClassModal';
import { useTelegram } from '@/components/providers/TelegramProvider';
import { Card, EmptyState, PageHeader, SkeletonRows } from '@/components/ui';

function Content(){const query=useSearchParams();const{refreshUser}=useTelegram();const[classes,setClasses]=React.useState<ClassItem[]>([]);const[loading,setLoading]=React.useState(true);const[error,setError]=React.useState('');const[open,setOpen]=React.useState(false);const[search,setSearch]=React.useState('');
 React.useEffect(()=>{if(query.get('create')==='true')setOpen(true)},[query]);
 const load=React.useCallback(()=>{setLoading(true);setError('');fetch('/api/classes').then(r=>r.json().then(d=>({ok:r.ok,d}))).then(({ok,d})=>{if(!ok||!d.success)throw new Error(d.error);setClasses(d.classes||[])}).catch(e=>setError(e.message||'Sinflarni yuklab bo‘lmadi')).finally(()=>setLoading(false))},[]);React.useEffect(load,[load]);
 const shown=classes.filter(c=>`${c.name} ${c.subject}`.toLowerCase().includes(search.toLowerCase()));
 return <div className="animate-page-in space-y-6"><PageHeader title="Sinflar" description={`${classes.length} ta sinf · ${classes.reduce((n,c)=>n+(c.student_count||0),0)} nafar o‘quvchi`} action={<button onClick={()=>setOpen(true)} className="flex min-h-11 shrink-0 items-center gap-2 rounded-[10px] bg-primary px-3.5 text-sm font-medium text-white"><Plus className="h-4 w-4"/><span className="hidden sm:inline">Yangi sinf</span></button>}/><label className="app-surface flex h-11 items-center gap-2 rounded-[10px] border px-3"><Search className="h-4 w-4 text-muted"/><span className="sr-only">Sinfni qidirish</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Sinf yoki fan bo‘yicha qidirish" className="w-full bg-transparent text-sm outline-none"/></label>{error&&<div role="alert" className="rounded-[10px] border border-red-200 bg-red-50 p-3 text-sm text-red-700 dark:border-red-900 dark:bg-red-950/30 dark:text-red-300">{error} <button onClick={load} className="ml-2 font-medium underline">Qayta urinish</button></div>}{loading?<SkeletonRows/>:classes.length===0?<EmptyState title="Hali sinf yaratilmagan" description="Sinf yarating va o‘quvchilarni boshqarishni boshlang." actionLabel="Sinf yaratish" onAction={()=>setOpen(true)}/>:<Card className="divide-y overflow-hidden">{shown.map(c=><Link key={c.id} href={`/sinflar/${c.id}`} className="group flex min-h-[84px] items-center gap-3 px-4 py-3 transition hover:app-muted sm:px-5"><div className="app-muted flex h-11 w-11 shrink-0 items-center justify-center rounded-[10px] text-sm font-semibold">{c.name}</div><div className="min-w-0 flex-1"><h2 className="truncate text-sm font-semibold">{c.name} sinf</h2><p className="mt-1 flex items-center gap-1.5 text-xs text-muted"><BookOpen className="h-3.5 w-3.5"/>{c.subject}</p></div><div className="hidden text-right sm:block"><p className="text-sm font-medium">{c.student_count||0} o‘quvchi</p><p className="mt-1 text-xs text-muted">Faol sinf</p></div><span className="app-muted flex h-9 w-9 items-center justify-center rounded-[9px]"><ArrowRight className="h-4 w-4 text-muted group-hover:text-primary"/></span></Link>)}{shown.length===0&&<div className="p-10 text-center text-sm text-muted">Qidiruv bo‘yicha sinf topilmadi.</div>}</Card>}<CreateClassModal isOpen={open} onClose={()=>setOpen(false)} onClassCreated={c=>{setClasses(x=>[c,...x]);refreshUser()}}/></div>}
export default function Page(){return <Suspense fallback={<SkeletonRows/>}><Content/></Suspense>}
