'use client';
import React from 'react';
import Link from 'next/link';
import { ArrowRight, Camera, FileCheck2, GraduationCap, ImagePlus, Users } from 'lucide-react';
import { useTelegram } from '@/components/providers/TelegramProvider';
import { Card, EmptyState, SectionTitle } from '@/components/ui';
import { ClassItem } from '@/lib/types';

export default function HomePage(){
 const {user,stats,isLoading,refreshUser}=useTelegram(); const [classes,setClasses]=React.useState<ClassItem[]>([]);
 React.useEffect(()=>{refreshUser();fetch('/api/classes').then(r=>r.json()).then(d=>setClasses(d.classes||[])).catch(()=>{});},[]);
 const name=(user?.full_name||'O‘qituvchi').split(' ')[0];
 return <div className="animate-page-in space-y-8">
  <section className="flex items-start justify-between gap-4"><div><p className="text-sm text-muted">Assalomu alaykum,</p><h1 className="mt-0.5 text-2xl font-semibold tracking-[-.03em] sm:text-[28px]">{isLoading?'…':name}</h1><p className="mt-2 text-sm text-muted">{user?.school_name||'Maktab o‘qituvchisi'}{user?.subject?` · ${user.subject}`:''}</p></div></section>
  <section><Card className="overflow-hidden"><div className="grid md:grid-cols-[1fr_auto]"><div className="p-5 sm:p-7"><span className="text-xs font-medium text-primary">YANGI TEKSHIRUV</span><h2 className="mt-2 text-xl font-semibold tracking-[-.02em]">Yangi ishni tekshirish</h2><p className="mt-1.5 max-w-lg text-sm leading-6 text-muted">Daftar, test yoki yozma ish rasmini yuklang. Natijani AI bilan tahlil qilib, o‘zingiz tasdiqlang.</p><div className="mt-5 flex flex-col gap-2 sm:flex-row"><Link href="/tekshirish" className="flex min-h-11 items-center justify-center gap-2 rounded-[10px] bg-primary px-4 text-sm font-medium text-white transition active:scale-[.98]"><ImagePlus className="h-4 w-4"/>Tekshirishni boshlash</Link><Link href="/tekshirish?camera=true" className="app-muted flex min-h-11 items-center justify-center gap-2 rounded-[10px] px-4 text-sm font-medium transition hover:opacity-80"><Camera className="h-4 w-4"/>Kamerani ochish</Link></div></div><div className="app-muted hidden w-48 items-center justify-center border-l md:flex"><div className="app-surface flex h-20 w-20 items-center justify-center rounded-[14px] border text-primary"><FileCheck2 className="h-9 w-9" strokeWidth={1.5}/></div></div></div></Card></section>
  <section><SectionTitle title="Ko‘rsatkichlar"/><div className="grid grid-cols-2 overflow-hidden rounded-[14px] border bg-[var(--border)] gap-px lg:grid-cols-4">{[
   ['Bugun tekshirildi',stats.todayChecked,FileCheck2],['Jami tekshirildi',stats.totalChecked,ArrowRight],['Sinflar',stats.classCount,GraduationCap],['O‘quvchilar',stats.studentCount,Users]
  ].map(([label,value,Icon]:any)=><div key={label} className="app-surface p-4 sm:p-5"><div className="flex items-center justify-between text-muted"><span className="text-xs font-medium">{label}</span><Icon className="h-4 w-4"/></div><p className="mt-3 text-2xl font-semibold tabular-nums">{value}</p><p className="mt-1 text-[11px] text-muted">Joriy holat</p></div>)}</div></section>
  <div className="grid gap-8 lg:grid-cols-[1.35fr_.65fr]"><section><SectionTitle title="So‘nggi tekshiruvlar" href="/tarix"/><EmptyState title="Hali tekshiruvlar yo‘q" description="Birinchi o‘quvchi ishini tekshiring — natijalar shu yerda ko‘rinadi." actionLabel="Tekshirishni boshlash" href="/tekshirish"/></section><section><SectionTitle title="Sinflar" href="/sinflar" linkLabel="Barcha sinflar"/>{classes.length===0?<EmptyState title="Hali sinf yo‘q" description="O‘quvchilarni boshqarish uchun sinf yarating." actionLabel="Sinf yaratish" href="/sinflar?create=true"/>:<Card className="divide-y">{classes.slice(0,4).map(c=><Link key={c.id} href={`/sinflar/${c.id}`} className="flex min-h-[72px] items-center gap-3 px-4 transition hover:app-muted"><div className="app-muted flex h-9 w-9 items-center justify-center rounded-[9px] text-xs font-semibold">{c.name}</div><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{c.name} · {c.subject}</p><p className="mt-0.5 text-xs text-muted">{c.student_count||0} o‘quvchi</p></div><ArrowRight className="h-4 w-4 text-muted"/></Link>)}</Card>}</section></div>
 </div>
}
