'use client';
import React from 'react';
import Link from 'next/link';
import { ArrowRight, CheckCircle2, FileCheck2, GraduationCap, Plus, ScanLine, UserPlus, Users } from 'lucide-react';
import { useTelegram } from '@/components/providers/TelegramProvider';
import { Card, EmptyState, SectionTitle } from '@/components/ui';
import { ClassItem } from '@/lib/types';

export default function HomePage(){
 const{user,stats,isLoading,refreshUser}=useTelegram();const[classes,setClasses]=React.useState<ClassItem[]>([]);const[recent,setRecent]=React.useState<any[]>([]);
 React.useEffect(()=>{refreshUser();Promise.all([fetch('/api/classes').then(r=>r.json()),fetch('/api/checks?limit=4').then(r=>r.json())]).then(([c,h])=>{setClasses(c.classes||[]);setRecent(h.checks||[])}).catch(()=>{})},[]);
 const name=(user?.full_name||'Ustoz').split(' ')[0];
 const next=stats.classCount===0?{title:'Avval sinf yarating',text:'Masalan: 7-A sinf, Matematika.',href:'/sinflar?create=true',label:'Sinf yaratish',icon:Plus}:stats.studentCount===0?{title:'Endi o‘quvchilarni qo‘shing',text:'Sinfni oching va o‘quvchilar ismini kiriting.',href:'/sinflar',label:'O‘quvchi qo‘shish',icon:UserPlus}:{title:'O‘quvchi ishini tekshiring',text:'Daftar yoki test rasmini yuklang. AI sizga tavsiya beradi.',href:'/tekshirish',label:'Ishni tekshirish',icon:ScanLine};
 const NextIcon=next.icon;
 return <div className="animate-page-in space-y-8"><section><p className="text-base text-muted">Assalomu alaykum,</p><h1 className="mt-1 text-3xl font-bold tracking-tight sm:text-4xl">{isLoading?'…':`${name} ustoz`}</h1><p className="mt-2 text-base text-muted">Bugun nima qilmoqchisiz?</p></section>
 <Card className="overflow-hidden border-2 border-[var(--primary)]"><div className="p-6 sm:p-8"><div className="flex items-start gap-4"><span className="flex h-14 w-14 shrink-0 items-center justify-center rounded-[14px] bg-primary text-white"><NextIcon className="h-7 w-7"/></span><div><p className="text-sm font-bold uppercase tracking-wide text-primary">Keyingi qadam</p><h2 className="mt-1 text-2xl font-bold">{next.title}</h2><p className="mt-2 max-w-xl text-base leading-7 text-muted">{next.text}</p></div></div><Link href={next.href} className="mt-6 flex min-h-14 w-full items-center justify-center gap-3 rounded-[12px] bg-primary px-6 text-lg font-bold text-white sm:w-fit"><NextIcon className="h-5 w-5"/>{next.label}<ArrowRight className="h-5 w-5"/></Link></div></Card>
 <section><SectionTitle title="Ishlash tartibi"/><div className="grid gap-3 md:grid-cols-3"><Step number="1" done={stats.classCount>0} title="Sinf yarating" text="Sinf nomi va fanini kiriting." href="/sinflar?create=true"/><Step number="2" done={stats.studentCount>0} title="O‘quvchi qo‘shing" text="Sinf ichiga o‘quvchilarni kiriting." href="/sinflar"/><Step number="3" done={stats.totalChecked>0} title="Ishni tekshiring" text="Rasm yuklang va natijani tasdiqlang." href="/tekshirish"/></div></section>
 <section><SectionTitle title="Qisqa ma’lumot"/><div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{[['Bugun tekshirildi',stats.todayChecked,FileCheck2],['Jami natijalar',stats.totalChecked,CheckCircle2],['Sinflar',stats.classCount,GraduationCap],['O‘quvchilar',stats.studentCount,Users]].map(([label,value,Icon]:any)=><Card key={label} className="p-5"><Icon className="h-6 w-6 text-primary"/><p className="mt-3 text-3xl font-bold tabular-nums">{value}</p><p className="mt-1 text-sm font-medium text-muted">{label}</p></Card>)}</div></section>
 <div className="grid gap-8 lg:grid-cols-2"><section><SectionTitle title="So‘nggi natijalar" href="/tarix" linkLabel="Barcha natijalar"/>{recent.length===0?<EmptyState title="Hali natija yo‘q" description="Birinchi ishni tekshirganingizdan so‘ng natija shu yerda ko‘rinadi." actionLabel="Ish tekshirish" href="/tekshirish"/>:<Card className="divide-y">{recent.map(x=>{const r=Array.isArray(x.results)?x.results[0]:x.results;return <div key={x.id} className="flex min-h-20 items-center gap-3 px-5 py-3"><div className="min-w-0 flex-1"><p className="truncate text-base font-semibold">{x.students?.full_name||'O‘quvchi'}</p><p className="mt-1 text-sm text-muted">{x.classes?.name||'Sinf'} · {new Date(x.created_at).toLocaleDateString('uz-UZ')}</p></div><p className="text-lg font-bold">{r?.approved?r.teacher_score:r?.ai_score??'—'} / {r?.approved?r.teacher_max_score:r?.ai_max_score??'—'}</p></div>})}</Card>}</section><section><SectionTitle title="Sinflaringiz" href="/sinflar"/>{classes.length===0?<EmptyState title="Hali sinf yo‘q" description="Boshlash uchun birinchi sinfingizni yarating." actionLabel="Sinf yaratish" href="/sinflar?create=true"/>:<Card className="divide-y">{classes.slice(0,4).map(c=><Link key={c.id} href={`/sinflar/${c.id}`} className="flex min-h-20 items-center gap-4 px-5"><div className="app-muted flex h-12 w-12 items-center justify-center rounded-[10px] text-base font-bold">{c.name}</div><div className="flex-1"><p className="text-base font-semibold">{c.name} · {c.subject}</p><p className="mt-1 text-sm text-muted">{c.student_count||0} nafar o‘quvchi</p></div><ArrowRight className="h-5 w-5 text-muted"/></Link>)}</Card>}</section></div></div>
}
function Step({number,done,title,text,href}:{number:string;done:boolean;title:string;text:string;href:string}){return <Link href={href}><Card className={`h-full p-5 transition hover:border-[var(--primary)] ${done?'border-emerald-400':''}`}><div className="flex items-center gap-3"><span className={`flex h-10 w-10 items-center justify-center rounded-full text-lg font-bold ${done?'bg-emerald-600 text-white':'app-muted text-primary'}`}>{done?<CheckCircle2 className="h-5 w-5"/>:number}</span><h3 className="text-lg font-bold">{title}</h3></div><p className="mt-3 text-base leading-7 text-muted">{text}</p></Card></Link>}
