import { NextRequest,NextResponse } from 'next/server';
import { z } from 'zod';
import { createAuthClient,authenticatedResponse,normalizePhone } from '@/lib/auth/account';
import { getSessionFromRequest } from '@/lib/auth/session';
import { isSupabaseConfigured,supabaseAdmin } from '@/lib/supabase/admin';
import { User } from '@/lib/types';
const schema=z.object({channel:z.enum(['phone','email']),value:z.string().min(5),token:z.string().regex(/^\d{6}$/),purpose:z.enum(['link','recover'])});
export async function POST(req:NextRequest){try{if(!isSupabaseConfigured)return NextResponse.json({error:'OTP xizmati sozlanmagan'},{status:503});const parsed=schema.safeParse(await req.json());if(!parsed.success)return NextResponse.json({error:'Kod yoki login ma’lumoti noto‘g‘ri'},{status:400});const{channel,token,purpose}=parsed.data;const value=channel==='phone'?normalizePhone(parsed.data.value):parsed.data.value.trim().toLowerCase();const auth=createAuthClient();const{data,error}=await auth.auth.verifyOtp(channel==='phone'?{phone:value,token,type:'sms'}:{email:value,token,type:'email'});if(error||!data.user)return NextResponse.json({error:'Kod noto‘g‘ri yoki muddati tugagan'},{status:400});const authUser=data.user;const identityField=channel==='phone'?'phone':'email';const identityValue=channel==='phone'?authUser.phone:authUser.email;const session=await getSessionFromRequest(req);
 let current:User|null=null;if(session){const{data}=await supabaseAdmin.from('users').select('*').eq('id',session.userId).maybeSingle();current=data as User|null}
 const{data:byAuth}=await supabaseAdmin.from('users').select('*').eq('auth_user_id',authUser.id).maybeSingle();const{data:byIdentity}=identityValue?await supabaseAdmin.from('users').select('*').eq(identityField,identityValue).maybeSingle():{data:null};let account=(byAuth||byIdentity) as User|null;
 if(purpose==='recover'&&!account)return NextResponse.json({error:'Bu ma’lumot bilan Tekshiradi AI akkaunti topilmadi'},{status:404});
 if(account&&current&&account.id!==current.id){if(current.telegram_id){await supabaseAdmin.from('users').update({telegram_id:null}).eq('id',current.id);const{error:linkError}=await supabaseAdmin.from('users').update({telegram_id:current.telegram_id,auth_user_id:authUser.id,[identityField]:identityValue}).eq('id',account.id);if(linkError)return NextResponse.json({error:'Telegram akkauntini ulashda xatolik'},{status:409});}if(!current.onboarding_completed)await supabaseAdmin.from('users').delete().eq('id',current.id);const{data:fresh}=await supabaseAdmin.from('users').select('*').eq('id',account.id).single();account=fresh as User;}
 else if(current){const{data:linked,error:linkError}=await supabaseAdmin.from('users').update({auth_user_id:authUser.id,[identityField]:identityValue}).eq('id',current.id).select('*').single();if(linkError)return NextResponse.json({error:'Login usulini ulab bo‘lmadi'},{status:409});account=linked as User;}
 else if(account){const{data:linked}=await supabaseAdmin.from('users').update({auth_user_id:authUser.id,[identityField]:identityValue}).eq('id',account.id).select('*').single();account=linked as User;}
 if(!account)return NextResponse.json({error:'Akkaunt topilmadi'},{status:404});const[{count:classes},{data:classRows}]=await Promise.all([supabaseAdmin.from('classes').select('*',{count:'exact',head:true}).eq('teacher_id',account.id),supabaseAdmin.from('classes').select('id').eq('teacher_id',account.id)]);let students=0;if(classRows?.length){const{count}=await supabaseAdmin.from('students').select('*',{count:'exact',head:true}).in('class_id',classRows.map(c=>c.id));students=count||0}return authenticatedResponse({user:account,restored:{classes:classes||0,students},isNewUser:!account.onboarding_completed},account);
 }catch(error){console.error('OTP verify error',error);return NextResponse.json({error:'Akkauntni tasdiqlashda xatolik'},{status:500})}}
