'use client';
import React from 'react';
import { Check, ChevronLeft, ImagePlus, Loader2, RotateCcw, ScanLine, Trash2, Upload } from 'lucide-react';
import { Card, PageHeader } from '@/components/ui';
import { ClassItem, Result, Student, TaskType } from '@/lib/types';

const types:{label:string,value:TaskType}[]=[{label:'Test',value:'test'},{label:'Yozma ish',value:'yozma'},{label:'Diktant',value:'diktant'},{label:'Uy vazifasi',value:'uy_vazifasi'},{label:'Boshqa',value:'boshqa'}];
const progress=['Rasm tahlil qilinmoqda','Matn aniqlanmoqda','Javoblar tekshirilmoqda','Natija tayyorlanmoqda'];
const toBase64=(file:File)=>new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onerror=()=>reject(new Error('Rasmni o\u2018qib bo\u2018lmadi'));r.onload=()=>resolve(String(r.result).split(',')[1]||'');r.readAsDataURL(file)});

export default function TekshirishPage(){
 const[step,setStep]=React.useState(1),[classes,setClasses]=React.useState<ClassItem[]>([]),[students,setStudents]=React.useState<Student[]>([]),[classId,setClassId]=React.useState(''),[studentId,setStudentId]=React.useState('');
 const[type,setType]=React.useState<TaskType>('test'),[instructions,setInstructions]=React.useState(''),[files,setFiles]=React.useState<{file:File,url:string}[]>([]),[index,setIndex]=React.useState(0),[result,setResult]=React.useState<Result|null>(null),[submissionId,setSubmissionId]=React.useState('');
 const[score,setScore]=React.useState(0),[maxScore,setMaxScore]=React.useState(20),[comment,setComment]=React.useState(''),[saved,setSaved]=React.useState(false),[saving,setSaving]=React.useState(false),[error,setError]=React.useState('');
 const filesRef=React.useRef(files);filesRef.current=files;
 React.useEffect(()=>{Promise.all([fetch('/api/classes').then(r=>r.json()),fetch('/api/me').then(r=>r.json())]).then(([c,m])=>{setClasses(c.classes||[]);setMaxScore(m.user?.preferences?.default_max_score||20)}).catch(()=>{})},[]);
 React.useEffect(()=>{if(!classId){setStudents([]);return}fetch(`/api/classes/${classId}/students`).then(r=>r.json()).then(d=>setStudents(d.students||[])).catch(()=>setStudents([]))},[classId]);
 React.useEffect(()=>()=>filesRef.current.forEach(x=>URL.revokeObjectURL(x.url)),[]);
 React.useEffect(()=>{if(step!==3)return;const timer=setInterval(()=>setIndex(i=>Math.min(3,i+1)),1500);return()=>clearInterval(timer)},[step]);
 const add=(list:FileList|null)=>{if(!list)return;const valid=Array.from(list).filter(f=>['image/jpeg','image/png','image/webp'].includes(f.type)&&f.size<=8*1024*1024);if(!valid.length){setError('Faqat JPG, PNG yoki WEBP (8 MB gacha) yuklang.');return}setError('');setFiles(old=>[...old,...valid.map(file=>({file,url:URL.createObjectURL(file)}))].slice(0,6));setStep(2)};
 const remove=(i:number)=>setFiles(old=>{URL.revokeObjectURL(old[i].url);return old.filter((_,j)=>i!==j)});
 const analyze=async()=>{setStep(3);setIndex(0);setError('');try{const images=await Promise.all(files.map(async x=>({data:await toBase64(x.file),mimeType:x.file.type})));const r=await fetch('/api/checks/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({classId,studentId,taskType:type,instructions,maxScore,images})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Tekshiruv bajarilmadi');setResult(d.result);setSubmissionId(d.submissionId);setScore(d.result.ai_score||0);setMaxScore(d.result.ai_max_score||maxScore);setStep(4)}catch(e){setError(e instanceof Error?e.message:'Tekshiruv bajarilmadi');setStep(2)}};
 const approve=async()=>{setSaving(true);setError('');try{const r=await fetch(`/api/checks/${submissionId}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({score,maxScore,comment})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Natija saqlanmadi');setSaved(true)}catch(e){setError(e instanceof Error?e.message:'Natija saqlanmadi')}finally{setSaving(false)}};
 const restart=()=>{files.forEach(x=>URL.revokeObjectURL(x.url));setStep(1);setFiles([]);setResult(null);setSaved(false);setError('')};
 const field='mt-1.5 min-h-11 w-full rounded-[10px] border bg-transparent px-3 text-sm outline-none focus:border-[var(--primary)]';
 return <div className="animate-page-in mx-auto max-w-3xl space-y-6"><PageHeader title="Ishni tekshirish" description="Natijani AI tayyorlaydi, yakuniy qarorni siz berasiz."/><div className="grid grid-cols-4 gap-2">{['Ma\u2019lumot','Rasm','Tahlil','Natija'].map((x,i)=><div key={x}><div className={`h-1 rounded-full ${step>i?'bg-primary':'app-muted'}`}/><p className="mt-2 text-[11px] text-muted">{i+1}. {x}</p></div>)}</div>{error&&<div role="alert" className="rounded-[10px] border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}
 {step===1&&<Card className="p-5 sm:p-6"><h2 className="font-semibold">Ish ma\u2019lumotlari</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-xs font-medium">Sinf<select className={field} value={classId} onChange={e=>{setClassId(e.target.value);setStudentId('')}}><option value="">Sinfni tanlang</option>{classes.map(c=><option key={c.id} value={c.id}>{c.name} · {c.subject}</option>)}</select></label><label className="text-xs font-medium">O‘quvchi<select className={field} value={studentId} onChange={e=>setStudentId(e.target.value)} disabled={!classId}><option value="">O‘quvchini tanlang</option>{students.map(s=><option key={s.id} value={s.id}>{s.full_name}</option>)}</select></label><div className="sm:col-span-2"><p className="text-xs font-medium">Ish turi</p><div className="mt-2 flex flex-wrap gap-2">{types.map(t=><button key={t.value} type="button" onClick={()=>setType(t.value)} className={`min-h-10 rounded-[9px] border px-3 text-sm ${type===t.value?'border-[var(--primary)] text-primary':''}`}>{t.label}</button>)}</div></div><label className="text-xs font-medium sm:col-span-2">Qo‘shimcha ko‘rsatma<textarea className={`${field} min-h-20 py-3`} value={instructions} onChange={e=>setInstructions(e.target.value)} placeholder="Masalan: har bir misol 2 ball"/></label><label className="text-xs font-medium">Maksimal ball<input className={field} type="number" min="1" max="1000" value={maxScore} onChange={e=>setMaxScore(Math.max(1,Number(e.target.value)))}/></label></div><button onClick={()=>setStep(2)} disabled={!classId||!studentId} className="mt-6 min-h-11 rounded-[10px] bg-primary px-4 text-sm font-medium text-white disabled:opacity-40">Davom etish</button></Card>}
 {step===2&&<Card className="p-5 sm:p-6"><div className="flex justify-between"><div><h2 className="font-semibold">O‘quvchi ishini yuklang</h2><p className="mt-1 text-sm text-muted">1–6 ta tiniq JPG, PNG yoki WEBP rasm.</p></div>{files.length>0&&<button onClick={()=>{files.forEach(x=>URL.revokeObjectURL(x.url));setFiles([])}} aria-label="Barchasini o‘chirish"><Trash2 className="h-4 w-4"/></button>}</div>{files.length===0?<label className="mt-5 flex min-h-64 cursor-pointer flex-col items-center justify-center rounded-[12px] border border-dashed"><input type="file" accept="image/jpeg,image/png,image/webp" multiple className="sr-only" onChange={e=>add(e.target.files)}/><Upload className="h-6 w-6 text-primary"/><span className="mt-4 text-sm font-medium">Rasm yuklash</span><span className="mt-1 text-xs text-muted">JPG, PNG yoki WEBP · 6 sahifagacha</span></label>:<div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-3">{files.map((x,i)=><div key={x.url} className="relative aspect-[4/5] overflow-hidden rounded-[12px] border"><img src={x.url} alt={`${i+1}-sahifa`} className="h-full w-full object-cover"/><button onClick={()=>remove(i)} aria-label="Rasmni o‘chirish" className="absolute right-2 top-2 flex h-9 w-9 items-center justify-center rounded-[9px] bg-black/60 text-white"><Trash2 className="h-4 w-4"/></button></div>)}{files.length<6&&<label className="app-muted flex aspect-[4/5] cursor-pointer flex-col items-center justify-center rounded-[12px] border border-dashed text-xs"><input type="file" accept="image/jpeg,image/png,image/webp" multiple className="sr-only" onChange={e=>add(e.target.files)}/><ImagePlus className="mb-2 h-5 w-5"/>Sahifa qo‘shish</label>}</div>}<div className="mt-6 flex gap-2"><button onClick={()=>setStep(1)} className="min-h-11 rounded-[10px] border px-4 text-sm"><ChevronLeft className="inline h-4 w-4"/> Orqaga</button><button onClick={analyze} disabled={!files.length} className="min-h-11 flex-1 rounded-[10px] bg-primary text-sm font-medium text-white disabled:opacity-40">AI tahlilini boshlash</button></div></Card>}
 {step===3&&<Card className="px-5 py-12 text-center"><div className="relative mx-auto h-14 w-14"><div className="absolute inset-0 animate-spin rounded-full border-2 border-transparent border-t-[var(--primary)]"/><ScanLine className="absolute inset-0 m-auto h-5 w-5 text-primary"/></div><h2 className="mt-5 font-semibold">{progress[index]}</h2><div className="mx-auto mt-7 max-w-sm space-y-3 text-left">{progress.map((x,i)=><div key={x} className={`flex items-center gap-3 text-sm ${i<=index?'':'text-muted'}`}><span className="app-muted flex h-6 w-6 items-center justify-center rounded-full">{i<index?<Check className="h-3.5 w-3.5"/>:i+1}</span>{x}</div>)}</div></Card>}
 {step===4&&result&&<div className="space-y-4"><Card className="p-5 sm:p-6"><span className="text-xs font-medium text-primary">AI TAVSIYASI</span><div className="mt-3 grid gap-5 sm:grid-cols-[1fr_auto]"><div><h2 className="text-lg font-semibold">Tekshiruv natijasi</h2><p className="mt-2 text-sm leading-6 text-muted">{result.ai_summary}</p><p className="mt-3 text-xs">Ishonchlilik: {Math.round((result.ai_confidence||0)*100)}%</p></div><div className="app-muted rounded-[12px] p-5 text-center"><span className="text-xs text-muted">Yakuniy ball</span><div><input aria-label="Ball" type="number" min="0" max={maxScore} value={score} onChange={e=>setScore(Number(e.target.value))} className="w-20 bg-transparent text-right text-4xl font-semibold outline-none"/><span className="text-lg text-muted"> / {maxScore}</span></div></div></div></Card><Card className="divide-y">{result.ai_mistakes?.length?result.ai_mistakes.map((m,i)=><div className="p-5" key={i}><h3 className="text-sm font-semibold">{m.question||`${i+1}-xato`}</h3><div className="mt-3 grid gap-2 sm:grid-cols-2"><div className="app-muted rounded-[10px] p-3 text-sm"><span className="text-xs text-muted">O‘quvchi javobi</span><p>{m.studentAnswer}</p></div><div className="app-muted rounded-[10px] p-3 text-sm"><span className="text-xs text-muted">To‘g‘ri javob</span><p>{m.correctAnswer}</p></div></div><p className="mt-3 text-sm">{m.explanation}</p></div>):<div className="p-5 text-sm text-muted">AI aniq xato topmadi. Natijani o‘zingiz ham tekshiring.</div>}<div className="p-5"><p className="mb-4 text-sm">{result.ai_feedback}</p><label className="text-xs font-medium">O‘qituvchi izohi<textarea value={comment} onChange={e=>setComment(e.target.value)} className="mt-2 min-h-24 w-full rounded-[10px] border bg-transparent p-3 text-sm"/></label></div></Card>{saved&&<div className="rounded-[10px] border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-800">Natija saqlandi</div>}<div className="flex gap-2"><button onClick={restart} className="flex min-h-11 items-center gap-2 rounded-[10px] border px-4 text-sm"><RotateCcw className="h-4 w-4"/>Yangi tekshiruv</button><button onClick={approve} disabled={saving||saved} className="min-h-11 flex-1 rounded-[10px] bg-primary text-sm font-medium text-white disabled:opacity-50">{saving?<Loader2 className="mx-auto h-4 w-4 animate-spin"/>:saved?'Tasdiqlandi':'Natijani tasdiqlash'}</button></div><p className="text-center text-xs text-muted">AI faqat tavsiya beradi. Yakuniy bahoni o‘qituvchi tasdiqlaydi.</p></div>}
 </div>
}
