'use client';
import React from 'react';
import { Check, ChevronLeft, ImagePlus, Loader2, ScanLine, Trash2, Upload } from 'lucide-react';
import { Card, PageHeader } from '@/components/ui';
import { ClassItem, Result, Student, TaskType } from '@/lib/types';

const types:{label:string,value:TaskType,hint:string}[]=[
 {label:'Test',value:'test',hint:'Javob varaqasi'},{label:'Yozma ish',value:'yozma',hint:'Masala va javoblar'},
 {label:'Diktant',value:'diktant',hint:'Imlo xatolari'},{label:'Uy vazifasi',value:'uy_vazifasi',hint:'Daftar ishi'},
 {label:'Boshqa',value:'boshqa',hint:'Erkin tekshiruv'},
];
type Work={file:File,url:string,studentId:string};
type Checked={submissionId:string,studentId:string,studentName:string,result:Result,score:number,maxScore:number,comment:string,saved:boolean,error?:string};
const toBase64=(file:File)=>new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onerror=()=>reject(new Error('Rasmni o‘qib bo‘lmadi'));r.onload=()=>resolve(String(r.result).split(',')[1]||'');r.readAsDataURL(file)});

export default function TekshirishPage(){
 const[step,setStep]=React.useState(0),[classes,setClasses]=React.useState<ClassItem[]>([]),[students,setStudents]=React.useState<Student[]>([]),[classId,setClassId]=React.useState('');
 const[type,setType]=React.useState<TaskType>('test'),[instructions,setInstructions]=React.useState(''),[maxScore,setMaxScore]=React.useState(20),[works,setWorks]=React.useState<Work[]>([]),[results,setResults]=React.useState<Checked[]>([]);
 const[completed,setCompleted]=React.useState(0),[savingAll,setSavingAll]=React.useState(false),[error,setError]=React.useState('');
 const worksRef=React.useRef(works);worksRef.current=works;
 React.useEffect(()=>{Promise.all([fetch('/api/classes').then(r=>r.json()),fetch('/api/me').then(r=>r.json())]).then(([c,m])=>{setClasses(c.classes||[]);setMaxScore(m.user?.preferences?.default_max_score||20)}).catch(()=>setError('Ma’lumotlarni yuklab bo‘lmadi'))},[]);
 React.useEffect(()=>{if(!classId){setStudents([]);return}fetch(`/api/classes/${classId}/students`).then(r=>r.json()).then(d=>setStudents(d.students||[])).catch(()=>setStudents([]))},[classId]);
 React.useEffect(()=>()=>worksRef.current.forEach(x=>URL.revokeObjectURL(x.url)),[]);
 const field='mt-1.5 min-h-11 w-full rounded-[10px] border bg-transparent px-3 text-sm outline-none focus:border-[var(--primary)]';
 const chosenClass=classes.find(c=>c.id===classId);
 const add=(list:FileList|null)=>{if(!list)return;const valid=Array.from(list).filter(f=>['image/jpeg','image/png','image/webp'].includes(f.type)&&f.size<=8*1024*1024);if(!valid.length){setError('Faqat JPG, PNG yoki WEBP (8 MB gacha) yuklang.');return}setError('');setWorks(old=>{const used=new Set(old.map(x=>x.studentId)),available=students.filter(s=>!used.has(s.id));return[...old,...valid.slice(0,30-old.length).map((file,i)=>({file,url:URL.createObjectURL(file),studentId:available[i]?.id||''}))]})};
 const remove=(i:number)=>setWorks(old=>{URL.revokeObjectURL(old[i].url);return old.filter((_,j)=>i!==j)});
 const setStudent=(i:number,studentId:string)=>setWorks(old=>old.map((x,j)=>i===j?{...x,studentId}:x));
 const analyze=async()=>{if(!works.length||works.some(x=>!x.studentId)){setError('Har bir rasm uchun o‘quvchini tanlang.');return}if(new Set(works.map(x=>x.studentId)).size!==works.length){setError('Bitta o‘quvchiga faqat bitta ish biriktiring.');return}setStep(3);setCompleted(0);setResults([]);setError('');const checked:Checked[]=[];for(const work of works){const student=students.find(s=>s.id===work.studentId);try{const data=await toBase64(work.file);const r=await fetch('/api/checks/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({classId,studentId:work.studentId,taskType:type,instructions,maxScore,images:[{data,mimeType:work.file.type}]})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Tekshiruv bajarilmadi');checked.push({submissionId:d.submissionId,studentId:work.studentId,studentName:student?.full_name||'O‘quvchi',result:d.result,score:d.result.ai_score||0,maxScore:d.result.ai_max_score||maxScore,comment:'',saved:false})}catch(e){checked.push({submissionId:'',studentId:work.studentId,studentName:student?.full_name||'O‘quvchi',result:{} as Result,score:0,maxScore,comment:'',saved:false,error:e instanceof Error?e.message:'Tekshiruv bajarilmadi'})}setCompleted(checked.length);setResults([...checked])}setStep(4)};
 const approve=async(i:number)=>{const x=results[i];if(!x.submissionId||x.saved)return;const r=await fetch(`/api/checks/${x.submissionId}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({score:x.score,maxScore:x.maxScore,comment:x.comment})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Natija saqlanmadi');setResults(old=>old.map((v,j)=>i===j?{...v,saved:true}:v))};
 const approveAll=async()=>{setSavingAll(true);setError('');try{for(let i=0;i<results.length;i++)if(!results[i].error&&!results[i].saved)await approve(i)}catch(e){setError(e instanceof Error?e.message:'Natijalarni saqlab bo‘lmadi')}finally{setSavingAll(false)}};
 const update=(i:number,patch:Partial<Checked>)=>setResults(old=>old.map((x,j)=>i===j?{...x,...patch}:x));
 const reset=()=>{works.forEach(x=>URL.revokeObjectURL(x.url));setWorks([]);setResults([]);setCompleted(0);setStep(0);setError('')};
 return <div className="animate-page-in mx-auto max-w-4xl space-y-6">
  <PageHeader title="AI tekshirish markazi" description="Butun sinf ishlarini bir martada yuklang va tekshiring."/>
  <div className="grid grid-cols-4 gap-2">{['Sinf','Rasmlar','Tekshirish','Natijalar'].map((x,i)=><div key={x}><div className={`h-1 rounded-full ${step>i?'bg-primary':'app-muted'}`}/><p className="mt-2 text-[11px] text-muted">{i+1}. {x}</p></div>)}</div>
  {error&&<div role="alert" className="rounded-[10px] border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}
  {step<3&&<Card className="divide-y overflow-hidden">
   <section className="p-5 sm:p-7"><div className="flex items-center gap-3"><span className="flex h-8 w-8 items-center justify-center rounded-[9px] bg-primary text-sm font-semibold text-white">1</span><h2 className="text-lg font-semibold">Sinfni tanlang</h2></div><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-3">{classes.map(c=><button key={c.id} onClick={()=>{setClassId(c.id);setWorks(old=>old.map(x=>({...x,studentId:''})))}} className={`min-h-20 rounded-[12px] border p-4 text-left transition ${classId===c.id?'border-[var(--primary)] bg-indigo-50 text-primary':'app-muted'}`}><span className="block font-semibold">{c.name}</span><span className="mt-1 block text-xs text-muted">{c.student_count||0} nafar o‘quvchi · {c.subject}</span></button>)}</div></section>
   <section className="p-5 sm:p-7"><div className="flex items-center gap-3"><span className="flex h-8 w-8 items-center justify-center rounded-[9px] bg-primary text-sm font-semibold text-white">2</span><h2 className="text-lg font-semibold">Topshiriq turini tanlang</h2></div><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-5">{types.map(t=><button key={t.value} onClick={()=>setType(t.value)} className={`min-h-20 rounded-[12px] border p-3 text-center transition ${type===t.value?'border-[var(--primary)] bg-primary text-white':''}`}><span className="block font-semibold">{t.label}</span><span className={`mt-1 block text-xs ${type===t.value?'text-white/75':'text-muted'}`}>{t.hint}</span></button>)}</div><div className="mt-4 grid gap-4 sm:grid-cols-[1fr_160px]"><label className="text-sm font-medium">Qo‘shimcha ko‘rsatma<input className={field} value={instructions} onChange={e=>setInstructions(e.target.value)} placeholder="Masalan: har bir misol 2 ball"/></label><label className="text-sm font-medium">Maksimal ball<input className={field} type="number" min="1" max="1000" value={maxScore} onChange={e=>setMaxScore(Math.max(1,Number(e.target.value)))}/></label></div></section>
   <section className="p-5 sm:p-7"><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-3"><span className="flex h-8 w-8 items-center justify-center rounded-[9px] bg-primary text-sm font-semibold text-white">3</span><h2 className="text-lg font-semibold">O‘quvchilar ishlarini yuklang</h2></div><span className="text-sm font-medium text-primary">{works.length} ta rasm tanlandi</span></div>{!classId?<div className="app-muted mt-5 rounded-[12px] border border-dashed p-10 text-center text-sm text-muted">Avval yuqoridan sinfni tanlang</div>:!students.length?<div className="app-muted mt-5 rounded-[12px] p-6 text-center text-sm text-muted">Bu sinfda o‘quvchilar yo‘q</div>:!works.length?<label className="mt-5 flex min-h-56 cursor-pointer flex-col items-center justify-center rounded-[14px] border-2 border-dashed text-center"><input type="file" accept="image/jpeg,image/png,image/webp" multiple className="sr-only" onChange={e=>add(e.target.files)}/><span className="flex h-14 w-14 items-center justify-center rounded-[12px] bg-indigo-50 text-primary"><Upload className="h-7 w-7"/></span><span className="mt-4 font-semibold">Barcha rasmlarni tanlang yoki shu yerga tashlang</span><span className="mt-1 text-sm text-muted">Kamera, galereya yoki kompyuterdan · 30 tagacha</span></label>:<div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{works.map((x,i)=><div key={x.url} className="overflow-hidden rounded-[12px] border"><div className="relative aspect-[4/3]"><img src={x.url} alt={`${i+1}-ish`} className="h-full w-full object-cover"/><span className="absolute left-2 top-2 rounded bg-black/70 px-2 py-1 text-xs text-white">{i+1}-ish</span><button onClick={()=>remove(i)} aria-label="Rasmni o‘chirish" className="absolute right-2 top-2 flex h-9 w-9 items-center justify-center rounded-[9px] bg-black/70 text-white"><Trash2 className="h-4 w-4"/></button></div><div className="p-3"><select aria-label={`${i+1}-rasm o‘quvchisi`} className={field} value={x.studentId} onChange={e=>setStudent(i,e.target.value)}><option value="">O‘quvchini tanlang</option>{students.map(s=><option key={s.id} value={s.id}>{s.full_name}</option>)}</select></div></div>)}{works.length<30&&<label className="app-muted flex min-h-40 cursor-pointer flex-col items-center justify-center rounded-[12px] border border-dashed text-sm"><input type="file" accept="image/jpeg,image/png,image/webp" multiple className="sr-only" onChange={e=>add(e.target.files)}/><ImagePlus className="mb-2 h-5 w-5"/>Yana rasm qo‘shish</label>}</div>}<button onClick={analyze} disabled={!classId||!works.length} className="mt-6 min-h-12 w-full rounded-[10px] bg-primary px-5 text-base font-semibold text-white disabled:opacity-40">{works.length} ta ishni AI orqali tekshirish</button></section>
  </Card>}
  {step===1&&<Card className="p-5 sm:p-6"><h2 className="text-lg font-semibold">1. Sinf va ish turini tanlang</h2><div className="mt-5 grid gap-5 sm:grid-cols-2"><label className="text-sm font-medium">Sinf<select className={field} value={classId} onChange={e=>setClassId(e.target.value)}><option value="">Sinfni tanlang</option>{classes.map(c=><option key={c.id} value={c.id}>{c.name} · {c.subject}</option>)}</select></label><label className="text-sm font-medium">Maksimal ball<input className={field} type="number" min="1" max="1000" value={maxScore} onChange={e=>setMaxScore(Math.max(1,Number(e.target.value)))}/></label><div className="sm:col-span-2"><p className="text-sm font-medium">Ish turi</p><div className="mt-2 grid grid-cols-2 gap-2 sm:grid-cols-5">{types.map(t=><button key={t.value} onClick={()=>setType(t.value)} className={`min-h-16 rounded-[10px] border p-3 text-left ${type===t.value?'border-[var(--primary)] text-primary':''}`}><span className="block text-sm font-medium">{t.label}</span><span className="mt-1 block text-[11px] text-muted">{t.hint}</span></button>)}</div></div><label className="text-sm font-medium sm:col-span-2">Qo‘shimcha ko‘rsatma<textarea className={`${field} min-h-20 py-3`} value={instructions} onChange={e=>setInstructions(e.target.value)} placeholder="Masalan: har bir misol 2 ball"/></label></div><button onClick={()=>setStep(2)} disabled={!classId||!students.length} className="mt-6 min-h-11 rounded-[10px] bg-primary px-5 text-sm font-medium text-white disabled:opacity-40">Davom etish</button>{classId&&!students.length&&<p className="mt-3 text-sm text-muted">Bu sinfga avval o‘quvchilar qo‘shing.</p>}</Card>}
  {step===2&&<Card className="p-5 sm:p-6"><h2 className="text-lg font-semibold">2. O‘quvchilar ishlarini yuklang</h2><p className="mt-1 text-sm text-muted">{chosenClass?.name} · Bir o‘quvchi uchun bitta rasm. 30 tagacha ish.</p>{!works.length?<label className="mt-5 flex min-h-64 cursor-pointer flex-col items-center justify-center rounded-[12px] border border-dashed text-center"><input type="file" accept="image/jpeg,image/png,image/webp" multiple className="sr-only" onChange={e=>add(e.target.files)}/><Upload className="h-7 w-7 text-primary"/><span className="mt-4 font-medium">Barcha rasmlarni tanlang</span><span className="mt-1 text-sm text-muted">Kamera, galereya yoki kompyuterdan</span></label>:<div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{works.map((x,i)=><div key={x.url} className="overflow-hidden rounded-[12px] border"><div className="relative aspect-[4/3]"><img src={x.url} alt={`${i+1}-ish`} className="h-full w-full object-cover"/><span className="absolute left-2 top-2 rounded bg-black/70 px-2 py-1 text-xs text-white">{i+1}-ish</span><button onClick={()=>remove(i)} aria-label="Rasmni o‘chirish" className="absolute right-2 top-2 flex h-9 w-9 items-center justify-center rounded-[9px] bg-black/70 text-white"><Trash2 className="h-4 w-4"/></button></div><div className="p-3"><label className="text-xs font-medium">O‘quvchi<select className={field} value={x.studentId} onChange={e=>setStudent(i,e.target.value)}><option value="">Tanlang</option>{students.map(s=><option key={s.id} value={s.id}>{s.full_name}</option>)}</select></label></div></div>)}{works.length<30&&<label className="app-muted flex min-h-40 cursor-pointer flex-col items-center justify-center rounded-[12px] border border-dashed text-sm"><input type="file" accept="image/jpeg,image/png,image/webp" multiple className="sr-only" onChange={e=>add(e.target.files)}/><ImagePlus className="mb-2 h-5 w-5"/>Yana rasm qo‘shish</label>}</div>}<div className="mt-6 flex gap-2"><button onClick={()=>setStep(1)} className="min-h-11 rounded-[10px] border px-4 text-sm"><ChevronLeft className="inline h-4 w-4"/> Orqaga</button><button onClick={analyze} disabled={!works.length} className="min-h-11 flex-1 rounded-[10px] bg-primary px-4 text-sm font-medium text-white disabled:opacity-40">{works.length} ta ishni AI orqali tekshirish</button></div></Card>}
  {step===3&&<Card className="px-5 py-12 text-center"><div className="relative mx-auto h-14 w-14"><div className="absolute inset-0 animate-spin rounded-full border-2 border-transparent border-t-[var(--primary)]"/><ScanLine className="absolute inset-0 m-auto h-5 w-5 text-primary"/></div><h2 className="mt-5 text-lg font-semibold">Ishlar tekshirilmoqda</h2><p className="mt-2 text-sm text-muted">{completed} / {works.length} ta ish tayyor</p><div className="mx-auto mt-6 h-2 max-w-sm overflow-hidden rounded-full app-muted"><div className="h-full bg-primary transition-all" style={{width:`${works.length?completed/works.length*100:0}%`}}/></div></Card>}
  {step===4&&<div className="space-y-4"><div className="flex items-end justify-between gap-3"><div><h2 className="text-xl font-semibold">Tekshiruv natijalari</h2><p className="mt-1 text-sm text-muted">{results.filter(x=>!x.error).length} ta ish tekshirildi</p></div><button onClick={approveAll} disabled={savingAll||results.every(x=>x.saved||x.error)} className="min-h-11 rounded-[10px] bg-primary px-4 text-sm font-medium text-white disabled:opacity-50">{savingAll?<Loader2 className="mx-auto h-4 w-4 animate-spin"/>:results.every(x=>x.saved||x.error)?'Saqlandi':'Barchasini tasdiqlash'}</button></div>{results.map((x,i)=><Card key={`${x.studentId}-${i}`} className="p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><h3 className="font-semibold">{x.studentName}</h3>{x.error?<p className="mt-2 text-sm text-red-600">{x.error}</p>:<><p className="mt-2 max-w-2xl text-sm leading-6 text-muted">{x.result.ai_summary}</p><p className="mt-2 text-xs text-muted">{x.result.ai_mistakes?.length||0} ta xato · Ishonchlilik {Math.round((x.result.ai_confidence||0)*100)}%</p></>}</div>{!x.error&&<div className="app-muted rounded-[10px] p-3"><input aria-label={`${x.studentName} balli`} type="number" min="0" max={x.maxScore} value={x.score} disabled={x.saved} onChange={e=>update(i,{score:Number(e.target.value)})} className="w-14 bg-transparent text-right text-2xl font-semibold outline-none"/><span className="text-sm text-muted"> / {x.maxScore}</span></div>}</div>{!x.error&&<div className="mt-4 flex items-end gap-2"><label className="flex-1 text-xs font-medium">O‘qituvchi izohi<input value={x.comment} disabled={x.saved} onChange={e=>update(i,{comment:e.target.value})} className={field} placeholder="Ixtiyoriy izoh"/></label><button onClick={()=>approve(i).catch(e=>setError(e.message))} disabled={x.saved} className="min-h-11 rounded-[10px] border px-4 text-sm font-medium disabled:opacity-50">{x.saved?<><Check className="mr-1 inline h-4 w-4"/>Saqlandi</>:'Tasdiqlash'}</button></div>}</Card>)}<button onClick={reset} className="min-h-11 rounded-[10px] border px-4 text-sm">Yangi tekshiruv</button><p className="text-center text-xs text-muted">AI tavsiya beradi. Yakuniy bahoni o‘qituvchi tasdiqlaydi.</p></div>}
 </div>
}
