'use client';
import React from 'react';
import { CheckCircle2,Mail,Phone,ShieldCheck } from 'lucide-react';
import { useRouter } from 'next/navigation';
import { Card } from '@/components/ui';
export default function RecoverPage(){const router=useRouter();const[channel,setChannel]=React.useState<'phone'|'email'>('phone');const[value,setValue]=React.useState('');const[token,setToken]=React.useState('');const[sent,setSent]=React.useState(false);const[busy,setBusy]=React.useState(false);const[error,setError]=React.useState('');const[restored,setRestored]=React.useState<{classes:number;students:number}|null>(null);
 const request=async()=>{setBusy(true);setError('');const r=await fetch('/api/auth/otp/send',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({channel,value,purpose:'recover'})});const d=await r.json();setBusy(false);if(!r.ok){setError(d.error);return}setSent(true)};
 const verify=async()=>{setBusy(true);setError('');const r=await fetch('/api/auth/otp/verify',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({channel,value,token,purpose:'recover'})});const d=await r.json();setBusy(false);if(!r.ok){setError(d.error);return}setRestored(d.restored);setTimeout(()=>router.push('/'),1800)};
 return <div className="animate-page-in mx-auto max-w-md py-6 sm:py-12"><div className="text-center"><span className="app-muted mx-auto flex h-12 w-12 items-center justify-center rounded-[11px] text-primary"><ShieldCheck className="h-6 w-6"/></span><h1 className="mt-5 text-2xl font-semibold">Akkauntni tiklash</h1><p className="mt-2 text-sm leading-6 text-muted">Tasdiqlangan telefon yoki email orqali barcha ma’lumotlaringizni qaytaring.</p></div><Card className="mt-7 p-5">{restored?<div className="py-6 text-center"><CheckCircle2 className="mx-auto h-10 w-10 text-emerald-600"/><h2 className="mt-4 text-lg font-semibold">Akkauntingiz topildi</h2><p className="mt-2 text-sm text-muted">{restored.classes} ta sinf va {restored.students} nafar o‘quvchi tiklandi.</p></div>:<><div className="grid grid-cols-2 gap-2"><Method active={channel==='phone'} onClick={()=>{setChannel('phone');setSent(false)}} icon={<Phone className="h-4 w-4"/>}>Telefon orqali</Method><Method active={channel==='email'} onClick={()=>{setChannel('email');setSent(false)}} icon={<Mail className="h-4 w-4"/>}>Email orqali</Method></div>{error&&<p role="alert" className="mt-4 rounded-[9px] bg-red-50 p-3 text-sm text-red-700 dark:bg-red-950/40 dark:text-red-300">{error}</p>}<label className="mt-5 block text-xs font-medium">{channel==='phone'?'Telefon raqam':'Email manzil'}<input value={value} onChange={e=>setValue(e.target.value)} placeholder={channel==='phone'?'+998 90 123 45 67':'siz@email.uz'} className="mt-1.5 min-h-11 w-full rounded-[10px] border bg-transparent px-3 text-sm outline-none"/></label>{sent&&<label className="mt-4 block text-xs font-medium">6 xonali kod<input value={token} onChange={e=>setToken(e.target.value.replace(/\D/g,'').slice(0,6))} inputMode="numeric" className="mt-1.5 min-h-11 w-full rounded-[10px] border bg-transparent px-3 text-center text-sm tracking-[.4em] outline-none" placeholder="000000"/></label>}<button onClick={sent?verify:request} disabled={busy||!value||(sent&&token.length!==6)} className="mt-5 min-h-11 w-full rounded-[10px] bg-primary text-sm font-medium text-white disabled:opacity-50">{busy?'Kutilmoqda...':sent?'Tasdiqlash va tiklash':'Kod yuborish'}</button></>}</Card><p className="mt-4 text-center text-xs text-muted">Ma’lumotlaringiz telefoningizda emas, akkauntingizda saqlanadi.</p></div>}
function Method({active,onClick,icon,children}:{active:boolean;onClick:()=>void;icon:React.ReactNode;children:React.ReactNode}){return <button onClick={onClick} className={`flex min-h-11 items-center justify-center gap-2 rounded-[9px] border text-xs font-medium ${active?'border-[var(--primary)] text-primary':''}`}>{icon}{children}</button>}
