'use client';
import React from 'react';
import { ClipboardList, Loader2, X } from 'lucide-react';
import { Student } from '@/lib/types';

export function AddStudentModal({isOpen,onClose,classId,onStudentsAdded,onStudentAdded}:{isOpen:boolean;onClose:()=>void;classId:string;onStudentsAdded?:(students:Student[])=>void;onStudentAdded?:(student:Student)=>void}){
 const[text,setText]=React.useState('');const[busy,setBusy]=React.useState(false);const[error,setError]=React.useState('');
 if(!isOpen)return null;
 const names=text.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);const unique=[...new Set(names)];
 const submit=async(e:React.FormEvent)=>{e.preventDefault();if(!unique.length){setError('Kamida bitta o‘quvchi ismini kiriting');return}setBusy(true);setError('');try{const r=await fetch(`/api/classes/${classId}/students`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({fullNames:unique})});const d=await r.json();if(!r.ok)throw new Error(d.error||'O‘quvchilar qo‘shilmadi');const added:Student[]=d.students||[];onStudentsAdded?.(added);added.forEach(student=>onStudentAdded?.(student));setText('');onClose()}catch(e){setError(e instanceof Error?e.message:'O‘quvchilar qo‘shilmadi')}finally{setBusy(false)}};
 return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-4"><div className="app-surface relative w-full max-w-xl rounded-[16px] border p-6 shadow-2xl"><button onClick={onClose} aria-label="Yopish" className="absolute right-4 top-4 flex h-10 w-10 items-center justify-center rounded-[10px] app-muted"><X className="h-5 w-5"/></button><div className="flex items-start gap-3 pr-12"><span className="app-muted flex h-12 w-12 shrink-0 items-center justify-center rounded-[12px] text-primary"><ClipboardList className="h-6 w-6"/></span><div><h2 className="text-xl font-bold">O‘quvchilarni birga qo‘shish</h2><p className="mt-1 text-base leading-6 text-muted">Har bir o‘quvchini yangi qatordan yozing. Excel ro‘yxatini ham ko‘chirib qo‘yishingiz mumkin.</p></div></div>{error&&<p role="alert" className="mt-4 rounded-[10px] bg-red-50 p-3 text-sm text-red-700 dark:bg-red-950/40 dark:text-red-300">{error}</p>}<form onSubmit={submit} className="mt-5"><label className="text-base font-semibold">O‘quvchilar ro‘yxati<textarea value={text} onChange={e=>setText(e.target.value)} autoFocus placeholder={'Ali Valiyev\nMadina Karimova\nJasur Rahimov'} className="mt-2 min-h-64 w-full resize-y rounded-[12px] border bg-transparent p-4 text-base leading-8 outline-none focus:border-[var(--primary)]"/></label><div className="mt-2 flex items-center justify-between text-sm text-muted"><span>Bitta ism — bitta qator</span><span>{unique.length} ta o‘quvchi</span></div><div className="mt-5 flex gap-3"><button type="button" onClick={onClose} className="min-h-12 rounded-[12px] border px-5 text-base font-semibold">Bekor qilish</button><button disabled={busy||!unique.length} className="flex min-h-12 flex-1 items-center justify-center gap-2 rounded-[12px] bg-primary px-5 text-base font-bold text-white disabled:opacity-40">{busy?<><Loader2 className="h-5 w-5 animate-spin"/>Qo‘shilmoqda…</>:`${unique.length} ta o‘quvchini qo‘shish`}</button></div></form></div></div>
}
