'use client';
import React from 'react';
import { ArrowLeft, ArrowRight, KeyRound, ScanLine, ShieldCheck } from 'lucide-react';
import { useTelegram } from '../providers/TelegramProvider';

const regions = [
  ['Toshkent shahri','Bektemir tumani,Chilonzor tumani,Mirobod tumani,Mirzo Ulug‘bek tumani,Olmazor tumani,Sergeli tumani,Shayxontohur tumani,Uchtepa tumani,Yakkasaroy tumani,Yangihayot tumani,Yashnobod tumani,Yunusobod tumani'],
  ['Toshkent viloyati','Angren shahri,Bekobod shahri,Chirchiq shahri,Nurafshon shahri,Ohangaron shahri,Olmaliq shahri,Yangiyo‘l shahri,Bekobod tumani,Bo‘ka tumani,Bo‘stonliq tumani,Chinoz tumani,Ohangaron tumani,Oqqo‘rg‘on tumani,Parkent tumani,Piskent tumani,Qibray tumani,Quyi Chirchiq tumani,Toshkent tumani,Yangiyo‘l tumani,Yuqori Chirchiq tumani,Zangiota tumani'],
  ['Andijon viloyati','Andijon shahri,Xonobod shahri,Andijon tumani,Asaka tumani,Baliqchi tumani,Bo‘ston tumani,Buloqboshi tumani,Izboskan tumani,Jalaquduq tumani,Marhamat tumani,Oltinko‘l tumani,Paxtaobod tumani,Qo‘rg‘ontepa tumani,Shahrixon tumani,Ulug‘nor tumani,Xo‘jaobod tumani'],
  ['Buxoro viloyati','Buxoro shahri,Kogon shahri,Buxoro tumani,G‘ijduvon tumani,Jondor tumani,Kogon tumani,Olot tumani,Peshku tumani,Qorako‘l tumani,Qorovulbozor tumani,Romitan tumani,Shofirkon tumani,Vobkent tumani'],
  ['Farg‘ona viloyati','Farg‘ona shahri,Qo‘qon shahri,Marg‘ilon shahri,Quvasoy shahri,Beshariq tumani,Bog‘dod tumani,Buvayda tumani,Dang‘ara tumani,Furqat tumani,Oltiariq tumani,O‘zbekiston tumani,Qo‘shtepa tumani,Quva tumani,Rishton tumani,So‘x tumani,Toshloq tumani,Uchko‘prik tumani,Yozyovon tumani'],
  ['Jizzax viloyati','Jizzax shahri,Arnasoy tumani,Baxmal tumani,Do‘stlik tumani,Forish tumani,G‘allaorol tumani,Jizzax tumani,Mirzacho‘l tumani,Paxtakor tumani,Sharof Rashidov tumani,Yangiobod tumani,Zafarobod tumani,Zarbdor tumani,Zomin tumani'],
  ['Namangan viloyati','Namangan shahri,Chortoq tumani,Chust tumani,Kosonsoy tumani,Mingbuloq tumani,Namangan tumani,Norin tumani,Pop tumani,To‘raqo‘rg‘on tumani,Uchqo‘rg‘on tumani,Uychi tumani,Yangiqo‘rg‘on tumani'],
  ['Navoiy viloyati','Navoiy shahri,Zarafshon shahri,G‘ozg‘on shahri,Karmana tumani,Konimex tumani,Navbahor tumani,Nurota tumani,Qiziltepa tumani,Tomdi tumani,Uchquduq tumani,Xatirchi tumani'],
  ['Qashqadaryo viloyati','Qarshi shahri,Shahrisabz shahri,Chiroqchi tumani,Dehqonobod tumani,G‘uzor tumani,Kasbi tumani,Kitob tumani,Koson tumani,Ko‘kdala tumani,Mirishkor tumani,Muborak tumani,Nishon tumani,Qamashi tumani,Qarshi tumani,Shahrisabz tumani,Yakkabog‘ tumani'],
  ['Qoraqalpog‘iston Respublikasi','Nukus shahri,Amudaryo tumani,Beruniy tumani,Bo‘zatov tumani,Chimboy tumani,Ellikqal‘a tumani,Kegeyli tumani,Mo‘ynoq tumani,Nukus tumani,Qanliko‘l tumani,Qo‘ng‘irot tumani,Qorao‘zak tumani,Shumanay tumani,Taxtako‘pir tumani,Taxiatosh tumani,To‘rtko‘l tumani,Xo‘jayli tumani'],
  ['Samarqand viloyati','Samarqand shahri,Kattaqo‘rg‘on shahri,Bulung‘ur tumani,Ishtixon tumani,Jomboy tumani,Kattaqo‘rg‘on tumani,Narpay tumani,Nurobod tumani,Oqdaryo tumani,Paxtachi tumani,Pastdarg‘om tumani,Payariq tumani,Qo‘shrabot tumani,Samarqand tumani,Toyloq tumani,Urgut tumani'],
  ['Sirdaryo viloyati','Guliston shahri,Shirin shahri,Yangiyer shahri,Boyovut tumani,Guliston tumani,Mirzaobod tumani,Oqoltin tumani,Sardoba tumani,Sayxunobod tumani,Sirdaryo tumani,Xovos tumani'],
  ['Surxondaryo viloyati','Termiz shahri,Angor tumani,Bandixon tumani,Boysun tumani,Denov tumani,Jarqo‘rg‘on tumani,Muzrabot tumani,Oltinsoy tumani,Qiziriq tumani,Qumqo‘rg‘on tumani,Sariosiyo tumani,Sherobod tumani,Sho‘rchi tumani,Termiz tumani,Uzun tumani'],
  ['Xorazm viloyati','Urganch shahri,Xiva shahri,Bog‘ot tumani,Gurlan tumani,Hazorasp tumani,Xiva tumani,Xonqa tumani,Qo‘shko‘pir tumani,Shovot tumani,Tuproqqal‘a tumani,Urganch tumani,Yangiariq tumani,Yangibozor tumani'],
] as const;
const subjects=['Matematika','Ona tili','Adabiyot','Ingliz tili','Rus tili','Informatika','Fizika','Kimyo','Biologiya','Tarix','Geografiya','Boshlang‘ich ta’lim','Boshqa'];

export function OnboardingModal(){
  const { user,tgUser,showOnboarding,updateUser,setShowOnboarding }=useTelegram();
  const [step,setStep]=React.useState(1); const [name,setName]=React.useState(user?.full_name||'');
  const [school,setSchool]=React.useState(user?.school_name||''); const [region,setRegion]=React.useState(user?.region||'');
  const [district,setDistrict]=React.useState(user?.district||''); const [subject,setSubject]=React.useState(user?.subject||'');
  const [loginName,setLoginName]=React.useState(user?.username||''); const [password,setPassword]=React.useState('');
  const [busy,setBusy]=React.useState(false); const [error,setError]=React.useState('');
  if(!showOnboarding)return null;
  const finish=async(nextUser=user)=>{setBusy(true);const r=await fetch('/api/auth/onboarding',{method:'PATCH'});const d=await r.json();setBusy(false);if(!r.ok){setError(d.error||'Yakunlab bo\u2018lmadi');return}updateUser(d.user||nextUser);setShowOnboarding(false)};
  const saveProfile=async()=>{if(!name.trim()||!region||!district||!subject){setError('Majburiy maydonlarni to‘ldiring');return}setBusy(true);const r=await fetch('/api/auth/onboarding',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({fullName:name.trim(),schoolName:school.trim()||null,region,district,subject})});const d=await r.json();setBusy(false);if(!r.ok){setError(d.error||'Profil saqlanmadi');return}setStep(3);setError('');updateUser(d.user);setShowOnboarding(true)};
  const saveLogin=async()=>{if(user?.username){await finish();return}setBusy(true);setError('');const r=await fetch('/api/auth/password',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:loginName.trim().toLowerCase(),password})});const d=await r.json();setBusy(false);if(!r.ok){setError(d.error||'Login ma\u2019lumotlari saqlanmadi');return}await finish(d.user)};
  return <div className="fixed inset-0 z-[80] overflow-y-auto bg-[var(--background)]"><div className="mx-auto flex min-h-full max-w-xl flex-col px-5 py-6 sm:justify-center sm:py-10">
    <div className="mb-8 flex items-center justify-between"><div className="flex items-center gap-2"><span className="flex h-9 w-9 items-center justify-center rounded-[10px] bg-primary text-white"><ScanLine className="h-4 w-4"/></span><span className="text-sm font-semibold">Tekshiradi AI</span></div><span className="text-xs text-muted">{step} / 3</span></div>
    <div className="mb-8 grid grid-cols-3 gap-2">{[1,2,3].map(x=><div key={x} className={`h-1 rounded-full ${x<=step?'bg-primary':'app-muted'}`}/>)}</div>
    {step===1&&<section className="animate-page-in text-center"><div className="app-muted mx-auto flex h-20 w-20 items-center justify-center rounded-full text-xl font-semibold">{tgUser?.first_name?.[0]||name[0]||'O‘'}</div><h1 className="mt-6 text-2xl font-semibold tracking-[-.03em]">Tekshiradi AI’ga xush kelibsiz</h1><p className="mx-auto mt-3 max-w-md text-sm leading-6 text-muted">O‘quvchilar ishlarini tezroq tekshiring va barcha natijalarni bir joyda saqlang.</p><button onClick={()=>setStep(2)} className="mt-8 flex min-h-11 w-full items-center justify-center gap-2 rounded-[10px] bg-primary text-sm font-medium text-white">Davom etish<ArrowRight className="h-4 w-4"/></button></section>}
    {step===2&&<section className="animate-page-in"><h1 className="text-2xl font-semibold">O‘qituvchi profili</h1><p className="mt-2 text-sm text-muted">Kundalik ishda kerak bo‘ladigan ma’lumotlar.</p><Error text={error}/><div className="mt-6 grid gap-4"><Field label="Ism va familiya"><input value={name} onChange={e=>setName(e.target.value)} className="field" placeholder="Aziza Karimova"/></Field><Field label="Maktab (ixtiyoriy)"><input value={school} onChange={e=>setSchool(e.target.value)} className="field" placeholder="Masalan: 23-maktab"/></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Viloyat"><select value={region} onChange={e=>{setRegion(e.target.value);setDistrict('')}} className="field"><option value="">Tanlang</option>{regions.map(r=><option key={r[0]}>{r[0]}</option>)}</select></Field><Field label="Tuman / shahar"><select value={district} onChange={e=>setDistrict(e.target.value)} className="field" disabled={!region}><option value="">Tanlang</option>{regions.find(r=>r[0]===region)?.[1].split(',').map(d=><option key={d}>{d}</option>)}</select></Field></div><Field label="Asosiy fan"><input list="subjects" value={subject} onChange={e=>setSubject(e.target.value)} className="field" placeholder="Fan nomini qidiring"/><datalist id="subjects">{subjects.map(s=><option key={s} value={s}/>)}</datalist></Field></div><div className="mt-7 flex gap-2"><button onClick={()=>setStep(1)} className="flex min-h-11 items-center gap-2 rounded-[10px] border px-4 text-sm"><ArrowLeft className="h-4 w-4"/>Orqaga</button><button onClick={saveProfile} disabled={busy} className="min-h-11 flex-1 rounded-[10px] bg-primary px-4 text-sm font-medium text-white">{busy?'Saqlanmoqda...':'Davom etish'}</button></div></section>}
    {step===3&&<section className="animate-page-in"><span className="app-muted flex h-12 w-12 items-center justify-center rounded-[11px] text-primary">{user?.username?<ShieldCheck className="h-6 w-6"/>:<KeyRound className="h-6 w-6"/>}</span><h1 className="mt-5 text-2xl font-semibold">{user?.username?'Akkauntingiz tayyor':'Username va parol yarating'}</h1><p className="mt-2 text-sm leading-6 text-muted">{user?.username?`Siz ${user.username} username bilan boshqa qurilmalardan ham kira olasiz.`:'Telegram bo‘lmasa ham akkauntingizga kirish uchun username va parol o‘rnating.'}</p><Error text={error}/>{!user?.username&&<div className="mt-6 space-y-4"><Field label="Username"><input value={loginName} onChange={e=>setLoginName(e.target.value.replace(/[^a-zA-Z0-9_]/g,'').toLowerCase())} className="field" placeholder="samar_ustoz" autoComplete="username"/></Field><Field label="Parol"><input value={password} onChange={e=>setPassword(e.target.value)} className="field" type="password" placeholder="Kamida 8 ta belgi" autoComplete="new-password"/></Field></div>}<button onClick={saveLogin} disabled={busy||(!user?.username&&(loginName.length<3||password.length<8))} className="mt-6 min-h-11 w-full rounded-[10px] bg-primary text-sm font-medium text-white disabled:opacity-40">{busy?'Saqlanmoqda...':user?.username?'Yakunlash':'Saqlash va yakunlash'}</button>{!user?.username&&<button onClick={()=>finish()} className="mt-3 min-h-11 w-full text-sm font-medium text-muted">Keyinroq</button>}</section>}
  </div><style jsx>{`.field{width:100%;min-height:44px;border:1px solid var(--border);border-radius:10px;background:transparent;padding:0 12px;font-size:14px;outline:none}.field:focus{border-color:var(--primary)}`}</style></div>;
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="text-xs font-medium">{label}<div className="mt-1.5">{children}</div></label>}
function Error({text}:{text:string}){return text?<p role="alert" className="mt-4 rounded-[10px] bg-red-50 p-3 text-sm text-red-700 dark:bg-red-950/40 dark:text-red-300">{text}</p>:null}
