import React from 'react';
import Link from 'next/link';
import { ArrowRight, Inbox } from 'lucide-react';

export function Card({ className='', children }:React.PropsWithChildren<{className?:string}>) { return <div className={`app-surface rounded-[14px] border ${className}`}>{children}</div>; }
export function PageHeader({ title, description, action }:{title:string;description?:string;action?:React.ReactNode}) { return <div className="flex items-start justify-between gap-4"><div><h1 className="text-xl font-semibold tracking-[-.02em] sm:text-2xl">{title}</h1>{description&&<p className="mt-1 text-sm text-muted">{description}</p>}</div>{action}</div>; }
export function EmptyState({ title,description,actionLabel,href,onAction }:{title:string;description:string;actionLabel?:string;href?:string;onAction?:()=>void}) { const cls='mt-5 inline-flex min-h-11 items-center justify-center rounded-[10px] bg-primary px-4 text-sm font-medium text-white transition active:scale-[.98]'; return <Card className="px-5 py-12 text-center"><div className="app-muted mx-auto flex h-11 w-11 items-center justify-center rounded-[10px] text-muted"><Inbox className="h-5 w-5"/></div><h3 className="mt-4 text-sm font-semibold">{title}</h3><p className="mx-auto mt-1 max-w-sm text-sm leading-6 text-muted">{description}</p>{actionLabel&&(href?<Link className={cls} href={href}>{actionLabel}</Link>:<button className={cls} onClick={onAction}>{actionLabel}</button>)}</Card>; }
export function SectionTitle({ title,href,linkLabel='Barchasini ko‘rish' }:{title:string;href?:string;linkLabel?:string}) { return <div className="mb-3 flex items-center justify-between"><h2 className="text-[15px] font-semibold">{title}</h2>{href&&<Link href={href} className="flex min-h-9 items-center gap-1 text-xs font-medium text-primary">{linkLabel}<ArrowRight className="h-3.5 w-3.5"/></Link>}</div>; }
export function SkeletonRows({ count=3 }:{count?:number}) { return <div className="space-y-2">{Array.from({length:count}).map((_,i)=><div key={i} className="app-surface flex h-20 items-center gap-3 rounded-[14px] border p-4"><div className="skeleton h-10 w-10 rounded-[10px]"/><div className="flex-1 space-y-2"><div className="skeleton h-3.5 w-32 rounded"/><div className="skeleton h-3 w-48 max-w-full rounded"/></div></div>)}</div>; }
